### ISSUE TITLE
서비스 이용 후기

### ISSUE THREAD

**Issue by David-Lee-dev** [ssafy-mate/ssafy-mate_service#3]
UI가 깔끔해서 사용하기 편리했습니다.

싸피에서 앞으로 이 앱을 이용해서 팀 구성을 진행했으면 좋겠어요. 앱을 이용하니 틱 구성하기 훨씬 쉽고 용이합니다.

**Comment by JeongHwan-dev** [comment]
안녕하세요 주현님 :) 

서비스 이용 후기 남겨주셔서 정말 감사합니다.  🙇

앞으로 더 사피 메이트 모바일 환경을 더 개선시켜 더 좋은 서비스를 제공해드리겠습니다.

후기 이벤트 참여를 완료하셔서 응모권 1장 적립되셨습니다.

다른 이벤트 참여도 많이 해주세요.  ☺️
